staticSites:
  - name: card-games-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
